import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>first-Nextpro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2 className='mt-20 font-bold'>Welcome to my First Next.js Project</h2>
      </div>
      <div className="badge">neutral</div>
      <div className="badge badge-primary">primary</div>
      <div className="badge badge-secondary">secondary</div>
      <div className="badge badge-accent">accent</div>
      <div className="badge badge-ghost">ghost</div>

     </div>
  )
}

export default Home
